// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VCashApp.Data;

#nullable disable

namespace VCashApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250729144949_AddCefModuleTables")]
    partial class AddCefModuleTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VCashApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("NombreUsuario");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasFilter("[NombreUsuario] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmCargo", b =>
                {
                    b.Property<int>("CodCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCargo"));

                    b.Property<bool>("Adicional")
                        .HasColumnType("bit");

                    b.Property<bool>("CentroCosto")
                        .HasColumnType("bit");

                    b.Property<string>("CodUnidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Extras")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("Jornada")
                        .HasColumnType("TIME(0)");

                    b.Property<string>("NombreCargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recargos")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("TiempoBreak")
                        .HasColumnType("TIME(0)");

                    b.HasKey("CodCargo");

                    b.HasIndex("CodUnidad");

                    b.ToTable("AdmCargos");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmCiudad", b =>
                {
                    b.Property<int>("CodCiudad")
                        .HasColumnType("int");

                    b.Property<string>("CodDepartamento")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodPais")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CodSucursal")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCiudad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodCiudad");

                    b.HasIndex("CodDepartamento");

                    b.HasIndex("CodPais");

                    b.HasIndex("CodSucursal");

                    b.ToTable("AdmCiudades");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmConcepto", b =>
                {
                    b.Property<int>("CodConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodConcepto"));

                    b.Property<string>("NombreConcepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoConcepto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodConcepto");

                    b.ToTable("AdmConceptos");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmConsecutivo", b =>
                {
                    b.Property<string>("TipoConsecutivo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("ConsecutivoActual")
                        .HasColumnType("bigint");

                    b.Property<long?>("Fin")
                        .HasColumnType("bigint");

                    b.Property<long?>("Inicio")
                        .HasColumnType("bigint");

                    b.Property<string>("LetraConsecutivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreConsecutivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoConsecutivo");

                    b.ToTable("AdmConsecutivos");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmDenominacion", b =>
                {
                    b.Property<int>("CodDenominacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodDenominacion"));

                    b.Property<int?>("CantidadUnidadAgrupamiento")
                        .HasColumnType("int");

                    b.Property<string>("Denominacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisaDenominacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamiliaDenominacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeclaAsociada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDenominacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDinero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadAgrupamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadExistencias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorDenominacion")
                        .HasColumnType("DECIMAL(18,0)");

                    b.HasKey("CodDenominacion");

                    b.ToTable("AdmDenominaciones");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmDepartamento", b =>
                {
                    b.Property<string>("CodDepartamento")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodPais")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreDepartamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodDepartamento");

                    b.HasIndex("CodPais");

                    b.ToTable("AdmDepartamentos");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmEmpleado", b =>
                {
                    b.Property<int>("CodCedula")
                        .HasColumnType("int");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CiudadExpedicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodCargo")
                        .HasColumnType("int");

                    b.Property<int?>("CodSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpleadoEstado")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FecRetiro")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FecVinculacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaExpedicion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("FirmaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IndicadorCatalogo")
                        .HasColumnType("bit");

                    b.Property<bool>("IngresoAeropuerto")
                        .HasColumnType("bit");

                    b.Property<bool>("IngresoRepublica")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCarnet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtroGenero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodCedula");

                    b.HasIndex("CodCargo");

                    b.HasIndex("CodSucursal");

                    b.ToTable("AdmEmpleados");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmEstado", b =>
                {
                    b.Property<int>("CodEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodEstado"));

                    b.Property<string>("NombreEstado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodEstado");

                    b.ToTable("AdmEstados");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmPais", b =>
                {
                    b.Property<string>("CodPais")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombrePais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Siglas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodPais");

                    b.ToTable("AdmPaises");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmRuta", b =>
                {
                    b.Property<string>("CodRutaSuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodRuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodSucursal")
                        .HasColumnType("int");

                    b.Property<bool>("Domingo")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("DomingoHoraFin")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeSpan?>("DomingoHoraInicio")
                        .HasColumnType("TIME(0)");

                    b.Property<bool>("EstadoRuta")
                        .HasColumnType("bit");

                    b.Property<bool>("Festivo")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("FestivoHoraFin")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeSpan?>("FestivoHoraInicio")
                        .HasColumnType("TIME(0)");

                    b.Property<bool>("Jueves")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("JuevesHoraFin")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeSpan?>("JuevesHoraInicio")
                        .HasColumnType("TIME(0)");

                    b.Property<bool>("Lunes")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("LunesHoraFin")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeSpan?>("LunesHoraInicio")
                        .HasColumnType("TIME(0)");

                    b.Property<bool>("Martes")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("MartesHoraFin")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeSpan?>("MartesHoraInicio")
                        .HasColumnType("TIME(0)");

                    b.Property<bool>("Miercoles")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("MiercolesHoraFin")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeSpan?>("MiercolesHoraInicio")
                        .HasColumnType("TIME(0)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("DECIMAL(18,0)");

                    b.Property<string>("NombreRuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sabado")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("SabadoHoraFin")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeSpan?>("SabadoHoraInicio")
                        .HasColumnType("TIME(0)");

                    b.Property<string>("TipoAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Viernes")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("ViernesHoraFin")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeSpan?>("ViernesHoraInicio")
                        .HasColumnType("TIME(0)");

                    b.HasKey("CodRutaSuc");

                    b.HasIndex("CodSucursal");

                    b.ToTable("AdmRutas");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmServicio", b =>
                {
                    b.Property<string>("OrdenServicio")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArchivoDetalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCiudadDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCiudadOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodCliente")
                        .HasColumnType("int");

                    b.Property<int?>("CodClienteDestino")
                        .HasColumnType("int");

                    b.Property<int?>("CodClienteOrigen")
                        .HasColumnType("int");

                    b.Property<int?>("CodConcepto")
                        .HasColumnType("int");

                    b.Property<string>("CodDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodEstado")
                        .HasColumnType("int");

                    b.Property<int?>("CodFlujo")
                        .HasColumnType("int");

                    b.Property<string>("CodOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodRangoDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodRangoOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodSucursal")
                        .HasColumnType("int");

                    b.Property<string>("CodSucursalDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodSucursalOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoOsCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Fallido")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("FechaAceptacion")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("FechaAtencionFinal")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("FechaAtencionInicial")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("FechaCancelacion")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("FechaProgramacion")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("FechaRechazo")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("FechaSolicitud")
                        .HasColumnType("DATE");

                    b.Property<TimeOnly?>("HoraAceptacion")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly?>("HoraAtencionFinal")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly?>("HoraAtencionInicial")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly?>("HoraCancelacion")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly?>("HoraProgramacion")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly?>("HoraRechazo")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly?>("HoraSolicitud")
                        .HasColumnType("TIME(0)");

                    b.Property<bool>("IndicadorDestinoTipo")
                        .HasColumnType("bit");

                    b.Property<bool>("IndicadorOrigenTipo")
                        .HasColumnType("bit");

                    b.Property<string>("IpOperador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModalidadServicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroBolsasMoneda")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroKitsCambio")
                        .HasColumnType("int");

                    b.Property<string>("NumeroPedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperadorCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperadorCgs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonaCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuntoDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PuntoOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableFallido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SucursalCgs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoConcepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTraslado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorBillete")
                        .HasColumnType("DECIMAL(18,0)");

                    b.Property<decimal?>("ValorMoneda")
                        .HasColumnType("DECIMAL(18,0)");

                    b.Property<decimal?>("ValorServicio")
                        .HasColumnType("DECIMAL(18,0)");

                    b.HasKey("OrdenServicio");

                    b.HasIndex("CodConcepto");

                    b.HasIndex("CodEstado");

                    b.HasIndex("CodSucursal");

                    b.ToTable("AdmServicios");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmSucursal", b =>
                {
                    b.Property<int>("CodSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodSucursal"));

                    b.Property<string>("CoSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodBancoRepublica")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("LatitudSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongitudSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiglasSucursal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodSucursal");

                    b.ToTable("AdmSucursales");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmUnidad", b =>
                {
                    b.Property<string>("CodUnidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreUnidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUnidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodUnidad");

                    b.ToTable("AdmUnidades");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmVehiculo", b =>
                {
                    b.Property<string>("CodVehiculo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Blindaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodSucursal")
                        .HasColumnType("int");

                    b.Property<string>("CodUnidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoVatco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConductorCedula")
                        .HasColumnType("int");

                    b.Property<string>("EmpresaAlquiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("GPS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontoAutorizado")
                        .HasColumnType("DECIMAL(18,0)");

                    b.Property<string>("NumeroChasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSoat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTecnomecanica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propiedad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Toneladas")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateOnly?>("VencimientoSoat")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("VencimientoTecnomecanica")
                        .HasColumnType("DATE");

                    b.HasKey("CodVehiculo");

                    b.HasIndex("CodSucursal");

                    b.HasIndex("CodUnidad");

                    b.HasIndex("ConductorCedula");

                    b.ToTable("AdmVehiculos");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmVista", b =>
                {
                    b.Property<string>("CodVista")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreVista")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RolAsociado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodVista");

                    b.ToTable("AdmVistas");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CefTransactionId")
                        .HasColumnType("int")
                        .HasColumnName("IdTransaccionCEF");

                    b.Property<int?>("ClientCashierId")
                        .HasColumnType("INT")
                        .HasColumnName("IdCajeroCliente");

                    b.Property<string>("ClientCashierName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NombreCajeroCliente");

                    b.Property<DateOnly?>("ClientEnvelopeDate")
                        .HasColumnType("DATE")
                        .HasColumnName("FechaSobreCliente");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CodigoContenedor");

                    b.Property<string>("ContainerStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstadoContenedor");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoContenedor");

                    b.Property<decimal>("CountedValue")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("ValorContado");

                    b.Property<decimal?>("DeclaredValue")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("ValorDeclarado");

                    b.Property<string>("Observations")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Observaciones");

                    b.Property<int?>("ParentContainerId")
                        .HasColumnType("int")
                        .HasColumnName("IdContenedorPadre");

                    b.Property<DateTime?>("ProcessingDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FechaProcesamiento");

                    b.Property<string>("ProcessingUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioProcesamientoId");

                    b.HasKey("Id");

                    b.HasIndex("CefTransactionId");

                    b.HasIndex("ParentContainerId");

                    b.HasIndex("ProcessingUserId");

                    b.ToTable("CefContenedores", (string)null);
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AffectedAmount")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("MontoAfectado");

                    b.Property<decimal>("AffectedDenomination")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("DenominacionAfectada");

                    b.Property<int?>("AffectedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("CantidadAfectada");

                    b.Property<int?>("CefContainerId")
                        .HasColumnType("int")
                        .HasColumnName("IdContenedorCef");

                    b.Property<int?>("CefTransactionId")
                        .HasColumnType("int")
                        .HasColumnName("IdTransaccionCef");

                    b.Property<int?>("CefValueDetailId")
                        .HasColumnType("int")
                        .HasColumnName("IdDetalleValorCef");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Descripcion");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FechaNovedad");

                    b.Property<string>("IncidentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstadoNovedad");

                    b.Property<int>("IncidentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoNovedad");

                    b.Property<string>("ReportedUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioReportaId");

                    b.HasKey("Id");

                    b.HasIndex("CefContainerId");

                    b.HasIndex("CefTransactionId");

                    b.HasIndex("CefValueDetailId");

                    b.HasIndex("IncidentTypeId");

                    b.HasIndex("ReportedUserId");

                    b.ToTable("CefNovedades", (string)null);
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefIncidentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AplicaPara");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("CefTiposNovedad", (string)null);
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CountingEndDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FechaFinConteo");

                    b.Property<DateTime?>("CountingStartDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FechaInicioConteo");

                    b.Property<int?>("CountingTableNumber")
                        .HasColumnType("int")
                        .HasColumnName("NumeroMesaConteo");

                    b.Property<string>("CountingUserBillId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioConteoBilletesId");

                    b.Property<string>("CountingUserCoinId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioConteoMonedasId");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Divisa");

                    b.Property<int>("DeclaredBagCount")
                        .HasColumnType("int")
                        .HasColumnName("CantidadBolsasDeclaradas");

                    b.Property<decimal>("DeclaredBillValue")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("ValorBilletesDeclarado");

                    b.Property<int>("DeclaredCheckCount")
                        .HasColumnType("int")
                        .HasColumnName("CantidadChequesDeclarados");

                    b.Property<decimal>("DeclaredCoinValue")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("ValorMonedasDeclarado");

                    b.Property<int>("DeclaredDocumentCount")
                        .HasColumnType("int")
                        .HasColumnName("CantidadDocumentosDeclarados");

                    b.Property<decimal>("DeclaredDocumentValue")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("ValorDocumentosDeclarado");

                    b.Property<int>("DeclaredEnvelopeCount")
                        .HasColumnType("int")
                        .HasColumnName("CantidadSobresDeclarados");

                    b.Property<string>("InformativeIncident")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NovedadInformativa");

                    b.Property<bool>("IsCustody")
                        .HasColumnType("bit")
                        .HasColumnName("EsCustodia");

                    b.Property<bool>("IsPointToPoint")
                        .HasColumnType("bit")
                        .HasColumnName("EsPuntoAPunto");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FechaUltimaActualizacion");

                    b.Property<string>("LastUpdateUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioUltimaActualizacionId");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FechaRegistro");

                    b.Property<string>("RegistrationIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPRegistro");

                    b.Property<string>("RegistrationUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioRegistroId");

                    b.Property<string>("ReviewerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioRevisorId");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("VARCHAR(12)")
                        .HasColumnName("CodRuta");

                    b.Property<string>("ServiceOrderId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("NVARCHAR(450)")
                        .HasColumnName("OrdenServicio");

                    b.Property<int>("SlipNumber")
                        .HasColumnType("int")
                        .HasColumnName("NumeroPlanilla");

                    b.Property<decimal>("TotalCountedValue")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("ValorTotalContado");

                    b.Property<string>("TotalCountedValueInWords")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ValorTotalContadoLetras");

                    b.Property<decimal>("TotalDeclaredValue")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("ValorTotalDeclarado");

                    b.Property<string>("TotalDeclaredValueInWords")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ValorTotalDeclaradoLetras");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstadoTransaccion");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoTransaccion");

                    b.Property<decimal>("ValueDifference")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("DiferenciaValor");

                    b.Property<string>("VaultUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioBovedaId");

                    b.HasKey("Id");

                    b.HasIndex("CountingUserBillId");

                    b.HasIndex("CountingUserCoinId");

                    b.HasIndex("LastUpdateUser");

                    b.HasIndex("RegistrationUser");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("VaultUserId");

                    b.ToTable("CefTransacciones", (string)null);
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefValueDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Banco");

                    b.Property<int?>("BundlesCount")
                        .HasColumnType("int")
                        .HasColumnName("CantidadFajos");

                    b.Property<decimal>("CalculatedAmount")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("MontoCalculado");

                    b.Property<int>("CefContainerId")
                        .HasColumnType("int")
                        .HasColumnName("IdContenedorCef");

                    b.Property<decimal>("Denomination")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("Denominacion");

                    b.Property<string>("IdentifierNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NumeroIdentificador");

                    b.Property<bool?>("IsHighDenomination")
                        .HasColumnType("bit")
                        .HasColumnName("EsAltaDenominacion");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("DATE")
                        .HasColumnName("FechaEmision");

                    b.Property<string>("Issuer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Emisor");

                    b.Property<int?>("LoosePiecesCount")
                        .HasColumnType("int")
                        .HasColumnName("CantidadPicos");

                    b.Property<string>("Observations")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Observaciones");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<decimal?>("UnitValue")
                        .HasColumnType("DECIMAL(18,0)")
                        .HasColumnName("ValorUnitario");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoValor");

                    b.HasKey("Id");

                    b.HasIndex("CefContainerId");

                    b.ToTable("CefDetallesValores", (string)null);
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CgsLocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreTipo");

                    b.HasKey("Id");

                    b.ToTable("CgsTiposUbicacion", (string)null);
                });

            modelBuilder.Entity("VCashApp.Models.Entities.PermisoPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodPerfilId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodVista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PerfilId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PuedeCrear")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeEditar")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeVer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CodPerfilId");

                    b.HasIndex("CodVista");

                    b.HasIndex("PerfilId");

                    b.ToTable("PermisosPerfil");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.SegRegistroEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodCargo")
                        .HasColumnType("int");

                    b.Property<int>("CodCedula")
                        .HasColumnType("int");

                    b.Property<int>("CodSucursal")
                        .HasColumnType("int");

                    b.Property<string>("CodUnidad")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("FechaEntrada")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("FechaSalida")
                        .HasColumnType("DATE");

                    b.Property<TimeOnly>("HoraEntrada")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly?>("HoraSalida")
                        .HasColumnType("TIME(0)");

                    b.Property<bool>("IndicadorEntrada")
                        .HasColumnType("bit");

                    b.Property<bool>("IndicadorSalida")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCargoEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSucursalEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUnidadEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellidoEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombreEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroUsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SegundoApellidoEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombreEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodCargo");

                    b.HasIndex("CodCedula");

                    b.HasIndex("CodSucursal");

                    b.HasIndex("CodUnidad");

                    b.HasIndex("RegistroUsuarioId");

                    b.ToTable("SegRegistroEmpleados");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.TdvRutaDiaria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(12)");

                    b.Property<int?>("CantBolsaBilleteEntrega")
                        .HasColumnType("int");

                    b.Property<int?>("CantBolsaBilleteRecibe")
                        .HasColumnType("int");

                    b.Property<int?>("CantBolsaMonedaEntrega")
                        .HasColumnType("int");

                    b.Property<int?>("CantBolsaMonedaRecibe")
                        .HasColumnType("int");

                    b.Property<int?>("CantPlanillaEntrega")
                        .HasColumnType("int");

                    b.Property<int?>("CantPlanillaRecibe")
                        .HasColumnType("int");

                    b.Property<int?>("CedulaConductor")
                        .HasColumnType("int");

                    b.Property<int?>("CedulaJT")
                        .HasColumnType("int");

                    b.Property<int?>("CedulaTripulante")
                        .HasColumnType("int");

                    b.Property<int?>("CodCargoConductor")
                        .HasColumnType("int");

                    b.Property<int?>("CodCargoJT")
                        .HasColumnType("int");

                    b.Property<int?>("CodCargoTripulante")
                        .HasColumnType("int");

                    b.Property<string>("CodRutaSuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CodSucursal")
                        .HasColumnType("int");

                    b.Property<string>("CodVehiculo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaCargue")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaDescargue")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaEjecucion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaEntradaRuta")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaIngresoJT")
                        .HasColumnType("DATE");

                    b.Property<DateOnly>("FechaPlaneacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaSalidaJT")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("FechaSalidaRuta")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HoraCargue")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraDescargue")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraEntradaRuta")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraIngresoJT")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly>("HoraPlaneacion")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraSalidaJT")
                        .HasColumnType("TIME(0)");

                    b.Property<TimeOnly?>("HoraSalidaRuta")
                        .HasColumnType("time");

                    b.Property<decimal?>("KmFinal")
                        .HasColumnType("NUMERIC(18,0)");

                    b.Property<decimal?>("KmInicial")
                        .HasColumnType("NUMERIC(18,0)");

                    b.Property<string>("NombreConductor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreJT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTripulante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCEFCargue")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioCEFDescargue")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioPlaneacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioSupervisorApertura")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioSupervisorCierre")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CedulaConductor");

                    b.HasIndex("CedulaJT");

                    b.HasIndex("CedulaTripulante");

                    b.HasIndex("CodCargoConductor");

                    b.HasIndex("CodCargoJT");

                    b.HasIndex("CodCargoTripulante");

                    b.HasIndex("CodRutaSuc");

                    b.HasIndex("CodSucursal");

                    b.HasIndex("CodVehiculo");

                    b.HasIndex("UsuarioCEFCargue");

                    b.HasIndex("UsuarioCEFDescargue");

                    b.HasIndex("UsuarioPlaneacion");

                    b.HasIndex("UsuarioSupervisorApertura");

                    b.HasIndex("UsuarioSupervisorCierre");

                    b.ToTable("TdvRutasDiarias");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmCargo", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.AdmUnidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("CodUnidad");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmCiudad", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.AdmDepartamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("CodDepartamento");

                    b.HasOne("VCashApp.Models.Entities.AdmPais", "Pais")
                        .WithMany()
                        .HasForeignKey("CodPais");

                    b.HasOne("VCashApp.Models.Entities.AdmSucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodSucursal");

                    b.Navigation("Departamento");

                    b.Navigation("Pais");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmDepartamento", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.AdmPais", "Pais")
                        .WithMany()
                        .HasForeignKey("CodPais");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmEmpleado", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.AdmCargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CodCargo");

                    b.HasOne("VCashApp.Models.Entities.AdmSucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodSucursal");

                    b.Navigation("Cargo");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmRuta", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.AdmSucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodSucursal");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmServicio", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.AdmConcepto", "Concepto")
                        .WithMany()
                        .HasForeignKey("CodConcepto");

                    b.HasOne("VCashApp.Models.Entities.AdmEstado", "Estado")
                        .WithMany()
                        .HasForeignKey("CodEstado");

                    b.HasOne("VCashApp.Models.Entities.AdmSucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodSucursal");

                    b.Navigation("Concepto");

                    b.Navigation("Estado");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.AdmVehiculo", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.AdmSucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodSucursal");

                    b.HasOne("VCashApp.Models.Entities.AdmUnidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("CodUnidad");

                    b.HasOne("VCashApp.Models.Entities.AdmEmpleado", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorCedula");

                    b.Navigation("Conductor");

                    b.Navigation("Sucursal");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefContainer", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.CefTransaction", "CefTransaction")
                        .WithMany("Containers")
                        .HasForeignKey("CefTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.Entities.CefContainer", "ParentContainer")
                        .WithMany("ChildContainers")
                        .HasForeignKey("ParentContainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ProcessingUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CefTransaction");

                    b.Navigation("ParentContainer");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefIncident", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.CefContainer", "CefContainer")
                        .WithMany("Incidents")
                        .HasForeignKey("CefContainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.CefTransaction", "CefTransaction")
                        .WithMany("Incidents")
                        .HasForeignKey("CefTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.CefValueDetail", "CefValueDetail")
                        .WithMany("Incidents")
                        .HasForeignKey("CefValueDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.CefIncidentType", "IncidentType")
                        .WithMany()
                        .HasForeignKey("IncidentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CefContainer");

                    b.Navigation("CefTransaction");

                    b.Navigation("CefValueDetail");

                    b.Navigation("IncidentType");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefTransaction", b =>
                {
                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CountingUserBillId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CountingUserCoinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("LastUpdateUser")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RegistrationUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.TdvRutaDiaria", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.AdmServicio", null)
                        .WithMany()
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("VaultUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefValueDetail", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.CefContainer", "CefContainer")
                        .WithMany("ValueDetails")
                        .HasForeignKey("CefContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CefContainer");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.PermisoPerfil", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("CodPerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.Entities.AdmVista", "Vista")
                        .WithMany()
                        .HasForeignKey("CodVista")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId");

                    b.Navigation("Perfil");

                    b.Navigation("Vista");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.SegRegistroEmpleado", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.AdmCargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CodCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.Entities.AdmEmpleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("CodCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.Entities.AdmSucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.Entities.AdmUnidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("CodUnidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.ApplicationUser", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("RegistroUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cargo");

                    b.Navigation("Empleado");

                    b.Navigation("Sucursal");

                    b.Navigation("Unidad");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.TdvRutaDiaria", b =>
                {
                    b.HasOne("VCashApp.Models.Entities.AdmEmpleado", "Conductor")
                        .WithMany()
                        .HasForeignKey("CedulaConductor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.AdmEmpleado", "JT")
                        .WithMany()
                        .HasForeignKey("CedulaJT")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.AdmEmpleado", "Tripulante")
                        .WithMany()
                        .HasForeignKey("CedulaTripulante")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.AdmCargo", "CargoConductorObj")
                        .WithMany()
                        .HasForeignKey("CodCargoConductor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.AdmCargo", "CargoJTObj")
                        .WithMany()
                        .HasForeignKey("CodCargoJT")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.AdmCargo", "CargoTripulanteObj")
                        .WithMany()
                        .HasForeignKey("CodCargoTripulante")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.Entities.AdmRuta", "RutaMaster")
                        .WithMany()
                        .HasForeignKey("CodRutaSuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.Entities.AdmSucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("CodSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VCashApp.Models.Entities.AdmVehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("CodVehiculo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VCashApp.Models.ApplicationUser", "UsuarioCEFCargueObj")
                        .WithMany()
                        .HasForeignKey("UsuarioCEFCargue");

                    b.HasOne("VCashApp.Models.ApplicationUser", "UsuarioCEFDescargueObj")
                        .WithMany()
                        .HasForeignKey("UsuarioCEFDescargue");

                    b.HasOne("VCashApp.Models.ApplicationUser", "UsuarioPlaneacionObj")
                        .WithMany()
                        .HasForeignKey("UsuarioPlaneacion");

                    b.HasOne("VCashApp.Models.ApplicationUser", "UsuarioSupervisorAperturaObj")
                        .WithMany()
                        .HasForeignKey("UsuarioSupervisorApertura");

                    b.HasOne("VCashApp.Models.ApplicationUser", "UsuarioSupervisorCierreObj")
                        .WithMany()
                        .HasForeignKey("UsuarioSupervisorCierre");

                    b.Navigation("CargoConductorObj");

                    b.Navigation("CargoJTObj");

                    b.Navigation("CargoTripulanteObj");

                    b.Navigation("Conductor");

                    b.Navigation("JT");

                    b.Navigation("RutaMaster");

                    b.Navigation("Sucursal");

                    b.Navigation("Tripulante");

                    b.Navigation("UsuarioCEFCargueObj");

                    b.Navigation("UsuarioCEFDescargueObj");

                    b.Navigation("UsuarioPlaneacionObj");

                    b.Navigation("UsuarioSupervisorAperturaObj");

                    b.Navigation("UsuarioSupervisorCierreObj");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("VCashApp.Models.ApplicationUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefContainer", b =>
                {
                    b.Navigation("ChildContainers");

                    b.Navigation("Incidents");

                    b.Navigation("ValueDetails");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefTransaction", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("VCashApp.Models.Entities.CefValueDetail", b =>
                {
                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
